### ISSUE TITLE
Add sound!

### ISSUE THREAD

**Issue by youngancient** [youngancient/techieQuiz#1]
I added sound but commented the code block out in the layout.tsx file because I haven't gotten a typescript doc that explains how to use howler with typescript.
There's currently a state called playQuizBgSound in redux/dataSlice, also there's an action toggling this.
The goal is to add:
1. Background sound when the user clicks start.
2. Play a short sound when the user fails or gets a question (while the background sound still plays)
3. Stop the bgsound when users click on finish and play a different celebration sound.
There's are sample sounds in the project. Pls utilize them and add others if necessary.

**Comment by Adedoyin-Emmanuel** [comment]
@youngancient assign this issue to me

**Comment by Adedoyin-Emmanuel** [comment]
Apparently, `Howler` wasn't built for `React` so I had issues working with it. Though there is another package built on top of `Howler` that supports react. But it had lots of issues and the aspect we needed for this game which is loading multiple sound files into the Howl() instance and dynamically controlling the sound volume and other props weren't supported also the `typed` definitions weren't in sync with the package.
